version: "3"

services:
    sftp:
        container_name: sftp
        image: christopherkuemmel/sftp
        build: .
        volumes:
            - ./data:/home
        ports:
            - "2222:22"
        cap_add:
            - SYS_ADMIN
